version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  
    volumes:
      - ./backend:/app
    environment:
      FLASK_APP: app
      FLASK_ENV: development  
      DATABASE_URL: mysql+pymysql://db_user:db_password@db/db_name
      SECRET_KEY: secret_key
    entrypoint: /bin/bash -c "flask db upgrade && flask run --host=0.0.0.0"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"  
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u db_user --password=db_password"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
