"""Add BlacklistedToken model for JWT blacklisting

Revision ID: 741558838ac4
Revises: 56fc8e71206b
Create Date: 2024-11-05 07:08:34.560798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741558838ac4'
down_revision = '56fc8e71206b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklisted_token')
    # ### end Alembic commands ###
