name: Static Analysis and E2E Testing

on:
  pull_request:
    branches: [main]

jobs:

  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js for Linting
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Step 3: Install frontend dependencies
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      # Step 4: Run ESLint on JavaScript Files
      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint

      # Step 5: Run StyleLint on CSS Files
      - name: Run StyleLint
        working-directory: ./frontend
        run: npm run stylelint

      # Step 6: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 7: Install Pylint
      - name: Install Pylint
        working-directory: ./backend
        run: pip install pylint

      # Step 8: Install dependencies from requirements.txt
      - name: Install dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt

      # Step 9: Run Pylint on Python Files
      # Only checks for errors (not warnings)
      # Ignores import-error rule
      - name: Run Pylint
        working-directory: ./backend
        run: pylint --errors-only --disable=import-error app/**/*.py

      # Step 10: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      
      # Step 11: Start the application with Docker Compose
      - name: Start services with Docker Compose
        run: docker-compose up -d  # Start services in detached mode

      # Step 12: Wait for the server to be ready
      - name: Wait for the server to be ready
        run: npx wait-on http://localhost:3000

      # Step 13: Run Cypress Tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v4
        with:
          install: true
          runTests: true

      # Step 14: Upload Cypress Screenshots as Artifacts
      - name: Upload Cypress Screenshots
        if: failure()  # Only upload if there was a failure
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots 
